coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%
