"""Type stubs for unittest.mock."""

from typing import Any

class _patch:
    """Mock patch context manager."""
    def __enter__(self) -> Any: ...
    def __exit__(self, *args: Any) -> None: ...
    def start(self) -> Any: ...
    def stop(self) -> None: ...

def patch(target: str, new: Any = None, **kwargs: Any) -> _patch: ...
