name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$(pwd)/src
          uv run pytest --cov=src --junitxml=pytest.xml --cov-report "xml:coverage.xml" --cov-report=term-missing --cov-config=pyproject.toml

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml

      - name: Run checks
        run: |
          uv run ruff check
          uv run ruff format
