name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$(pwd)/src
          uv pytest --cov=src --cov-report=html --cov-report=term-missing --cov-config=pyproject.toml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

      - name: Run checks
        run: |
          uv ruff check
          uv ruff format
