name: Release Tests

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

env:
  WHISPER_MODEL_NAME: "tiny" # Set the default Whisper model name for tests

jobs:
  test-release:
    runs-on: ${{ matrix.os }}
    if: ${{ contains(github.event.workflow_run.head_branch, 'v') && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Wait for PyPI to update
        run: sleep 60

      - name: Install waddle from PyPI
        run: |
          pip install --upgrade pip
          pip install waddle-ai

      - uses: emptymap/setup-ffmpeg@5644f1ea8a58c026223ed8d5147314e7fb7ae3ba
        id: setup-ffmpeg
        with:
          ffmpeg-version: 7.0.2
      # - name: Test waddle install
      #   run: |
      #     waddle install

      - name: Test waddle preprocess
        run: |
          waddle preprocess --directory tests/ep0 --output /tmp/preprocess_out -t 10 --no-convert
          # Check that output files were created
          ls /tmp/preprocess_out/*.wav || (echo "No WAV files created by preprocess" && exit 1)

      - name: Test waddle postprocess
        run: |
          waddle postprocess --directory /tmp/preprocess_out --output /tmp/postprocess_out -t 5
          # Check that output WAV files were created
          ls /tmp/postprocess_out/*.wav || (echo "No WAV files created by postprocess" && exit 1)
          # Check that SRT transcription files were created
          ls /tmp/postprocess_out/*.srt || (echo "No SRT files created by postprocess" && exit 1)
          echo "Release tests completed successfully!"
